apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: prometheus
    tier: monitoring
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  selector:
    matchLabels:
      app: prometheus
      tier: monitoring
  template:
    metadata:
      labels:
        app: prometheus
        tier: monitoring
    spec:
      containers:
      - name: prometheus
        image: arealmaas/prometheus-kubernetes
        imagePullPolicy: Always
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 9090
