apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    tier: monitoring
  name: prometheus
  namespace: default
spec:
  ports:
    targetPort: 9090
  selector:
    app: prometheus
    tier: monitoring
  type: LoadBalancer
