apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-management-web
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: user-management
    tier: web
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  # selector can be applied automatically
  # from the labels in the pod template if not set
  selector:
    matchLabels:
      app: user-management
      tier: web
  template:
    metadata:
      labels:
        app: user-management
        tier: web
    spec:
      containers:
      - name: groovy-user-management
        image: arealmaas/groovy-user-management
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 3000
