web:
  build: .
  command: npm start
  volumes:
   - .:/code
  expose:
     - "3000"
  links:
   - mongo:mongo
   - redis:redis
mongo:
  image: mongo
redis:
  image: redis
lb:
  image: 'dockercloud/haproxy:latest'
  links:
    - web
  ports:
    - '80'
